name: Push (dev), Pull Request
on:
  push:
    branches: ["**"]
  pull_request:
jobs:
  lint-python:
    name: Run Python lint
    uses: kuba2k2/kuba2k2/.github/workflows/lint-python.yml@master
  test-python:
    name: Run Python tests
    uses: kuba2k2/kuba2k2/.github/workflows/test-python.yml@master
